### ISSUE TITLE
일부 컬럼 길이 제한은 하지 않는 건가요?

### ISSUE THREAD

**Issue by flynnpark** [Type-Any/Any-Poem#23]
[User 엔티티](https://github.com/Type-Any/Any-Poem/blob/develop/backend/src/entities/User.ts)의 이름이나 이메일 같은 필드에는 길이 제한을 두지 않는 건가유?

만약 길이 제한을 하실 거라면 제가 한 번 풀리퀘를 날려보도록 하겠습니다...

**Comment by mununki** [comment]
PR. 환영합니다
